export const serviceAccountInfo = [
  {
    id: 1,
    age: '20 days',
    creationDate: '01/01/2019 18:00 PST',
    status: 'Active',
    publicKey: [
      { action: '', label: 'View' },
      { action: '', label: 'Copy' },
      { action: '', label: 'Download' },
    ],
    actions: [
      { type: 'red', label: 'De-Activate' },
    ],
  },
  {
    id: 2,
    age: '5 days',
    creationDate: '09/09/2021 02:00 PST',
    status: 'Active',
    publicKey: [
      { action: '', label: 'View' },
      { action: '', label: 'Copy' },
      { action: '', label: 'Download' },
    ],
    actions: [
      { type: 'red', label: 'De-Activate' },
      { type: 'red', label: 'Archive' },
    ],
  },
  {
    id: 3,
    age: '18 days',
    creationDate: '04/04/2022 21:00 PST',
    status: 'Inactive',
    publicKey: [
      { action: '', label: 'View' },
      { action: '', label: 'Copy' },
      { action: '', label: 'Download' },
    ],
    actions: [
      { type: 'green', label: 'Re-Activate' },
    ],
  },
];

export const environmentServiceList = [
  {
    id: 1,
    identifier: 'Access API',
    activeKeys: 81,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
    permission: 'Full Access',
  },
  {
    id: 2,
    identifier: 'Bank API',
    activeKeys: 51,
    roles: 'Global Access',
    oldestActiveKeyAge: '5 Weeks',
    permission: 'Full Access',
  },
  {
    id: 3,
    identifier: 'Mock API',
    activeKeys: 16,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Years',
    permission: 'Full Access',
  },
];

export const manageAccountList = [
  {
    id: 1,
    identifier: 'Access API',
    activeKeys: 81,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 2,
    identifier: 'Bank API',
    activeKeys: 51,
    roles: 'Global Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 3,
    identifier: 'Mock API',
    activeKeys: 16,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 4,
    identifier: 'Mock API',
    activeKeys: 18,
    roles: 'Global Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 5,
    identifier: 'Access API',
    activeKeys: 55,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 6,
    identifier: 'Bank API',
    activeKeys: 53,
    roles: 'No Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 7,
    identifier: 'Mock API',
    activeKeys: 83,
    roles: 'Development Access',
    oldestActiveKeyAge: '1 Month',
  },
  {
    id: 8,
    identifier: 'Bank API',
    activeKeys: 84,
    roles: 'No Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 9,
    identifier: 'Fraud API',
    activeKeys: 75,
    roles: 'User Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 10,
    identifier: 'Mock API',
    activeKeys: 52,
    roles: 'Development Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 11,
    identifier: 'Security API',
    activeKeys: 13,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 12,
    identifier: 'Mock API',
    activeKeys: 74,
    roles: 'No Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 13,
    identifier: 'Fraud API',
    activeKeys: 14,
    roles: 'User Access',
    oldestActiveKeyAge: '1 Month',
  },
  {
    id: 14,
    identifier: 'Security API',
    activeKeys: 71,
    roles: 'Development Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 15,
    identifier: 'Mock API',
    activeKeys: 38,
    roles: 'User Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 16,
    identifier: 'Fraud API',
    activeKeys: 91,
    roles: 'User Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 17,
    identifier: 'Mock API',
    activeKeys: 75,
    roles: 'Development Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 18,
    identifier: 'Mock API',
    activeKeys: 82,
    roles: 'User Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 19,
    identifier: 'Access API',
    activeKeys: 23,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 20,
    identifier: 'Fraud API',
    activeKeys: 36,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 21,
    identifier: 'Bank API',
    activeKeys: 93,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 22,
    identifier: 'Mock API',
    activeKeys: 56,
    roles: 'User Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 23,
    identifier: 'Security API',
    activeKeys: 21,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 24,
    identifier: 'Security API',
    activeKeys: 88,
    roles: 'No Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 25,
    identifier: 'Security API',
    activeKeys: 3,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 26,
    identifier: 'Fraud API',
    activeKeys: 64,
    roles: 'User Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 27,
    identifier: 'Access API',
    activeKeys: 75,
    roles: 'Development Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 28,
    identifier: 'Security API',
    activeKeys: 47,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 29,
    identifier: 'Bank API',
    activeKeys: 61,
    roles: 'User Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 30,
    identifier: 'Access API',
    activeKeys: 80,
    roles: 'No Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 31,
    identifier: 'Mock API',
    activeKeys: 10,
    roles: 'User Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 32,
    identifier: 'Bank API',
    activeKeys: 9,
    roles: 'Development Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 33,
    identifier: 'Security API',
    activeKeys: 56,
    roles: 'Global Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 34,
    identifier: 'Mock API',
    activeKeys: 61,
    roles: 'Global Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 35,
    identifier: 'Security API',
    activeKeys: 2,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Month',
  },
  {
    id: 36,
    identifier: 'Fraud API',
    activeKeys: 61,
    roles: 'No Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 37,
    identifier: 'Security API',
    activeKeys: 3,
    roles: 'Global Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 38,
    identifier: 'Access API',
    activeKeys: 15,
    roles: 'No Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 39,
    identifier: 'Bank API',
    activeKeys: 42,
    roles: 'Global Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 40,
    identifier: 'Fraud API',
    activeKeys: 61,
    roles: 'Global Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 41,
    identifier: 'Fraud API',
    activeKeys: 81,
    roles: 'User Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 42,
    identifier: 'Access API',
    activeKeys: 43,
    roles: 'Development Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 43,
    identifier: 'Access API',
    activeKeys: 70,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 44,
    identifier: 'Access API',
    activeKeys: 3,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 45,
    identifier: 'Mock API',
    activeKeys: 58,
    roles: 'Global Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 46,
    identifier: 'Bank API',
    activeKeys: 100,
    roles: 'User Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 47,
    identifier: 'Access API',
    activeKeys: 65,
    roles: 'User Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 48,
    identifier: 'Bank API',
    activeKeys: 32,
    roles: 'User Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 49,
    identifier: 'Fraud API',
    activeKeys: 46,
    roles: 'User Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 50,
    identifier: 'Access API',
    activeKeys: 12,
    roles: 'User Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 51,
    identifier: 'Access API',
    activeKeys: 49,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 52,
    identifier: 'Mock API',
    activeKeys: 82,
    roles: 'User Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 53,
    identifier: 'Mock API',
    activeKeys: 38,
    roles: 'Global Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 54,
    identifier: 'Fraud API',
    activeKeys: 25,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 55,
    identifier: 'Security API',
    activeKeys: 34,
    roles: 'Global Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 56,
    identifier: 'Mock API',
    activeKeys: 40,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 57,
    identifier: 'Bank API',
    activeKeys: 31,
    roles: 'No Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 58,
    identifier: 'Fraud API',
    activeKeys: 60,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 59,
    identifier: 'Access API',
    activeKeys: 42,
    roles: 'Global Access',
    oldestActiveKeyAge: '3 Years',
  },
  {
    id: 60,
    identifier: 'Mock API',
    activeKeys: 25,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 61,
    identifier: 'Access API',
    activeKeys: 81,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 62,
    identifier: 'Access API',
    activeKeys: 89,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 63,
    identifier: 'Bank API',
    activeKeys: 86,
    roles: 'Global Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 64,
    identifier: 'Access API',
    activeKeys: 21,
    roles: 'Development Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 65,
    identifier: 'Bank API',
    activeKeys: 1,
    roles: 'Development Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 66,
    identifier: 'Access API',
    activeKeys: 58,
    roles: 'Global Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 67,
    identifier: 'Access API',
    activeKeys: 67,
    roles: 'Development Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 68,
    identifier: 'Mock API',
    activeKeys: 22,
    roles: 'User Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 69,
    identifier: 'Fraud API',
    activeKeys: 95,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 70,
    identifier: 'Access API',
    activeKeys: 41,
    roles: 'Global Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 71,
    identifier: 'Bank API',
    activeKeys: 29,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Week',
  },
  {
    id: 72,
    identifier: 'Bank API',
    activeKeys: 87,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 73,
    identifier: 'Access API',
    activeKeys: 37,
    roles: 'Global Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 74,
    identifier: 'Bank API',
    activeKeys: 18,
    roles: 'User Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 75,
    identifier: 'Fraud API',
    activeKeys: 85,
    roles: 'No Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 76,
    identifier: 'Access API',
    activeKeys: 58,
    roles: 'No Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 77,
    identifier: 'Mock API',
    activeKeys: 79,
    roles: 'Development Access',
    oldestActiveKeyAge: '6 Weeks',
  },
  {
    id: 78,
    identifier: 'Security API',
    activeKeys: 59,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 79,
    identifier: 'Bank API',
    activeKeys: 48,
    roles: 'Global Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 80,
    identifier: 'Access API',
    activeKeys: 63,
    roles: 'Global Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 81,
    identifier: 'Mock API',
    activeKeys: 33,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 82,
    identifier: 'Access API',
    activeKeys: 52,
    roles: 'User Access',
    oldestActiveKeyAge: '5 Weeks',
  },
  {
    id: 83,
    identifier: 'Bank API',
    activeKeys: 13,
    roles: 'Development Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 84,
    identifier: 'Access API',
    activeKeys: 99,
    roles: 'User Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 85,
    identifier: 'Fraud API',
    activeKeys: 58,
    roles: 'No Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 86,
    identifier: 'Security API',
    activeKeys: 15,
    roles: 'Development Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 87,
    identifier: 'Security API',
    activeKeys: 31,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 88,
    identifier: 'Security API',
    activeKeys: 26,
    roles: 'Global Access',
    oldestActiveKeyAge: '11 Months',
  },
  {
    id: 89,
    identifier: 'Security API',
    activeKeys: 25,
    roles: 'Development Access',
    oldestActiveKeyAge: '3 Weeks',
  },
  {
    id: 90,
    identifier: 'Access API',
    activeKeys: 94,
    roles: 'No Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 91,
    identifier: 'Access API',
    activeKeys: 29,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 92,
    identifier: 'Mock API',
    activeKeys: 48,
    roles: 'User Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 93,
    identifier: 'Security API',
    activeKeys: 50,
    roles: 'No Access',
    oldestActiveKeyAge: '2 Months',
  },
  {
    id: 94,
    identifier: 'Bank API',
    activeKeys: 1,
    roles: 'Global Access',
    oldestActiveKeyAge: '12 Days',
  },
  {
    id: 95,
    identifier: 'Fraud API',
    activeKeys: 15,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Month',
  },
  {
    id: 96,
    identifier: 'Bank API',
    activeKeys: 63,
    roles: 'Development Access',
    oldestActiveKeyAge: '2 Years',
  },
  {
    id: 97,
    identifier: 'Security API',
    activeKeys: 45,
    roles: 'User Access',
    oldestActiveKeyAge: '11 Days',
  },
  {
    id: 98,
    identifier: 'Bank API',
    activeKeys: 23,
    roles: 'Global Access',
    oldestActiveKeyAge: '1 Month',
  },
  {
    id: 99,
    identifier: 'Fraud API',
    activeKeys: 80,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
  },
  {
    id: 100,
    identifier: 'Access API',
    activeKeys: 20,
    roles: 'Global Access',
    oldestActiveKeyAge: '23 Days',
  },
];
