export const user = {
  name: 'John Doe',
  isUserAuthenticated: true,
};

export const environmentUsersList = [
  {
    id: 1,
    name: 'Ashby Sherrott',
    email: 'asherrott0@wsj.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 2,
    name: 'Rafaellle Allawy',
    email: 'rallawy1@fastcompany.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 3,
    name: 'Irvin McParlin',
    email: 'imcparlin2@jiathis.com',
    status: 'Pending',
    permission: 'Global access',
  },
];

export const manageUsersList = [
  {
    id: 1,
    name: 'Ashby Sherrott',
    email: 'asherrott0@wsj.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 2,
    name: 'Rafaellle Allawy',
    email: 'rallawy1@fastcompany.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 3,
    name: 'Irvin McParlin',
    email: 'imcparlin2@jiathis.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 4,
    name: 'Crista Keinrat',
    email: 'ckeinrat3@typepad.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 5,
    name: 'Nan Fox',
    email: 'nfox4@hao123.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 6,
    name: 'Guthrey Addison',
    email: 'gaddison5@i2i.jp',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 7,
    name: 'Guglielma Krabbe',
    email: 'gkrabbe6@arstechnica.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 8,
    name: 'Veda MacDermott',
    email: 'vmacdermott7@de.vu',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 9,
    name: 'Torre Fortin',
    email: 'tfortin8@umn.edu',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 10,
    name: 'Whitney Sparway',
    email: 'wsparway9@flickr.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 11,
    name: 'Georgina Labrom',
    email: 'glabroma@amazon.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 12,
    name: 'Cassius Clementucci',
    email: 'cclementuccib@networksolutions.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 13,
    name: 'Lionello Clardge',
    email: 'lclardgec@jugem.jp',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 14,
    name: 'Emilee Tonkin',
    email: 'etonkind@wikipedia.org',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 15,
    name: 'Fernande Murkitt',
    email: 'fmurkitte@timesonline.co.uk',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 16,
    name: 'Kimmy McInally',
    email: 'kmcinallyf@blog.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 17,
    name: 'Yelena Vincent',
    email: 'yvincentg@bing.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 18,
    name: 'Janice Hardison',
    email: 'jhardisonh@tamu.edu',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 19,
    name: 'Michaella Blanckley',
    email: 'mblanckleyi@indiatimes.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 20,
    name: 'Pincas Arnholdt',
    email: 'parnholdtj@clickbank.net',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 21,
    name: 'Hiram Poxson',
    email: 'hpoxsonk@irs.gov',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 22,
    name: 'Gian Edeler',
    email: 'gedelerl@abc.net.au',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 23,
    name: 'Daren Nealand',
    email: 'dnealandm@go.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 24,
    name: 'Osbourn Benoy',
    email: 'obenoyn@wix.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 25,
    name: 'Gayel Langton',
    email: 'glangtono@un.org',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 26,
    name: "Rodge O'Grogane",
    email: 'rogroganep@ucsd.edu',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 27,
    name: 'Vida Pea',
    email: 'vpeaq@guardian.co.uk',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 28,
    name: 'Joycelin Stanbridge',
    email: 'jstanbridger@bravesites.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 29,
    name: 'Beatriz Iston',
    email: 'bistons@github.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 30,
    name: 'Georgine Mirralls',
    email: 'gmirrallst@webnode.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 31,
    name: 'Dagmar Crackett',
    email: 'dcrackettu@mapquest.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 32,
    name: 'Hagen Fulle',
    email: 'hfullev@cnbc.com',
    status: 'Pending',
    permission: 'Global access',
  },
  {
    id: 33,
    name: 'Pryce Wardhaw',
    email: 'pwardhaww@sun.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 34,
    name: 'Ashia McTavish',
    email: 'amctavishx@jimdo.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 35,
    name: 'Urbano Jurasz',
    email: 'ujuraszy@redcross.org',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 36,
    name: 'Deirdre Lauthian',
    email: 'dlauthianz@businessinsider.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 37,
    name: 'Tamara Filer',
    email: 'tfiler10@google.es',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 38,
    name: 'Liz Bernini',
    email: 'lbernini11@nhs.uk',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 39,
    name: 'Enriqueta Annets',
    email: 'eannets12@umn.edu',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 40,
    name: 'Bambie Santora',
    email: 'bsantora13@sfgate.com',
    status: 'Accepted',
    permission: 'Local access',
  },
  {
    id: 41,
    name: 'Gerrard Marley',
    email: 'gmarley14@patch.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 42,
    name: 'Brendan Justun',
    email: 'bjustun15@posterous.com',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 43,
    name: 'Tish Orry',
    email: 'torry16@rediff.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 44,
    name: 'Gualterio Roze',
    email: 'groze17@omniture.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 45,
    name: 'Jamie Willox',
    email: 'jwillox18@sina.com.cn',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 46,
    name: 'Arie Hundey',
    email: 'ahundey19@usa.gov',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 47,
    name: 'Sayres Fassbender',
    email: 'sfassbender1a@goodreads.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 48,
    name: 'Noelle Burgot',
    email: 'nburgot1b@sina.com.cn',
    status: 'Accepted',
    permission: 'Global access',
  },
  {
    id: 49,
    name: 'Kayley Medlen',
    email: 'kmedlen1c@networksolutions.com',
    status: 'Pending',
    permission: 'Local access',
  },
  {
    id: 50,
    name: 'Jane Bladder',
    email: 'jbladder1d@sciencedirect.com',
    status: 'Pending',
    permission: 'Local access',
  },
];
